#!/bin/sh
###adsl-on v0.1
###     - active adsl connection
###     - Written by root, 2008-08-26
###Usage:
###     adsl-on [interface name]
###Option:
###     -h Display help text
###Example:
###     adsl-on
scripthelp "$0" "$@" && exit 0

ifn=dsl-provider
sudo-unless-root poff -a
sudo-unless-root pon "$ifn"
sleep 3
sudo-unless-root ifconfig


