#!/bin/bash

#Script Name:	amstatus
#Date:		Mon Dec 18 21:06:37 CST 2006
#AUTHOR:	duel


# COLOR
NOR="\033[0m"
BOLD="\033[1m"
RED="\033[91m"
YEL="\033[93m"
GRE="\033[92m"



APPNAME="amstatus"
APPVER="0.1"
APPDESC="show Amule daemon status"
APPUSAGE=""
EXAMPLE=""


ARGS=$*

if [ "$ARGS" = "-h" ] ;then
	echo "$APPNAME V$APPVER"
	echo -e "\t $APPDESC"
	echo -e " -h\tDisplay this."
	echo -e " -e\tWhere am I." 
	echo -e "Usage: $0 $APPUSAGE"
	if [ ! -z "$EXAMPLE" ];then 
	    echo -e "Example: $EXAMPLE"
	fi
	exit 0
fi

if [ "$1" = "-e" ] ; then
    echo $0
    exit 0
fi

#while [ 1 ]; do
  domule() {
    amulecmd -P newfreedom -c "$@" | grep "^ >"
  }
  domule "show dl" | grep "^ > [0-9a-zA-Z]\+" | sed -e "s/^ > [0-9a-zA-Z]\+/ >/"
  echo ""
  domule "show log" | sed "
  /: Failed to / {s/: \(.*\)/: `tput setaf 1`\1`tput sgr0`/;}
  /: Finished downloading/ {s/: \(.*\)/: `tput setaf 2`\1`tput sgr0`/;}
  /: Downloading / {s/: \(.*\)/: `tput setaf 3`\1`tput sgr0`/;}
  "
  echo ""
  domule "status" | sed "
  /Download:/ {s/\(Download:\)\(.*\)/\1`tput setaf 3`\2`tput sgr0`/;}
  /Upload:/ {s/\(Upload:\)\(.*\)/\1`tput setaf 2`\2`tput sgr0`/;}
  "
  echo ""
  domule "reset" >/dev/null
#  sleep 1m
#done

