#!/bin/bash

APPNAME="basefname"
APPVER="0.1"
APPDESC="return the basename without ext suffix from a file name."
APPUSAGE="(filename)"

ARGS=$*

if [ -z "$ARGS" ] || [ "$ARGS" = "-h" ] ;then
	echo "$APPNAME V$APPVER"
	echo -e "\t $APPDESC"
	echo -e "Usage: $0 $APPUSAGE"
	exit 0
fi

FILENAME="$*"
EXTNAME=`extname "$FILENAME"`
basename -- "$FILENAME" "$EXTNAME"
