#!/bin/bash
#TEMPLATE BEGIN
APPNAME="btjoblist"
APPAUTHOR="duel"
APPDATE="2007-03-28"
APPVER="0.1"
APPDESC="List all delayed btjob"
APPUSAGE="[JOBNAME]"
EXAMPLE="btjoblist \"*.done\""

# NOCOLOR
NOR=;BOLD=;RED=;YEL=;GRE=
# COLOR
NOR="\033[0m";BOLD="\033[1m";RED="\033[91m";YEL="\033[93m";GRE="\033[92m"
# FUNCTIONS
function APPMSG() { if [ -n "$*" ] ; then echo -e $GRE"$*"$NOR ; fi ; } 
function APPMSG2() { if [ -n "$*" ] ; then APPMSG "\t$*" ; fi ; }
function APPWARN() { if [ -n "$*" ] ; then echo -e $RED"$*"$NOR ; fi ; }
function DisplayUsage() {
    APPMSG "$APPNAME V$APPVER\n  Written by $APPAUTHOR AT $APPDATE"
    APPMSG "$APPDESC"
    APPMSG " -h\tDisplay this information.\n -E\tEdit me."
    APPMSG "Usage: $0 $APPUSAGE"
    if [ -n "$EXAMPLE" ] ; then APPMSG "Example: $EXAMPLE" ; fi
    exit 1 
}
ARGS=$*
for i in $ARGS ; do
    case $i in 
        "-h" ) DisplayUsage ;;
        "-E" ) vim $0 ; exit $? ;;
    esac
done
#TEMPLATE END
BTJOBS=/share/appdata/btjob
echo "BTJobs[$BTJOBS]:"
if [ -z "$ARGS" ]; then
    find "$BTJOBS" -type f -name "*.done" | sed -e "s!$BTJOBS/!!g" 
    find "$BTJOBS" -type f -name "*.delay" | sed -e "s!$BTJOBS/!!g"
else
    find "$BTJOBS" -type f -name "$1" | sed -e "s!$BTJOBS/!!g" 
fi



