#!/bin/sh

if [ -z "$*" ] ; then
	find . -type d -print0 | xargs -0 chmod -v 775
	find . -type f -print0 | xargs -0 chmod -v 664 
else
	while [ -n "$1" ] ; do
		find "$1" -type d -print0 | xargs -0 chmod -v 775
		find "$1" -type f -print0 | xargs -0 chmod -v 664 
		shift
	done
fi	
