#!/bin/sh
#LANG="zh_CN.UTF-8" WINEDEBUG="+loaddll" wine "$@"
#LANG="zh_CN.UTF-8" WINEDEBUG="+loaddll" wine "$@" 2>&1 | color_print_wine



export LANGUAGE="zh_CN.UTF-8"
export LC_ALL="zh_CN.UTF-8"
export LANG="zh_CN.UTF-8"

wine regedit - 2>/dev/null <<EOF
REGEDIT4

[HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\FontSubstitutes]
"MS Shell Dlg"="unifont"
"MS Shell Dlg 2"="unifont"
"Tahoma"="unifont"
"Tms Rmn"="Times New Roman"
EOF

if [ -z "$NODEBUG" ] ; then
    export WINEDEBUG="+loaddll,$WINEDEBUG"
    exec wine "$@" 2>&1 | color_print_wine #| tee "$HOME/wine.log" | color_print_wine
else
    exec wine "$@" 2>/dev/null 1>/dev/null
fi

#export LANG="zh_CN.UTF-8"
#export LANGUAGE="zh_CN.UTF-8"
#exec wine "$@"
#LANG="zh_CN.UTF-8"
#export LANG
#exec wine "$@"
#LANG="zh_CN.GBK" wine "$@"
