#!/bin/sh
###copymbr v0.1
###     - copymbr
###     - Written by xiaoranzzz, 2009-06-18
###Usage:
###     copymbr
###Option:
###     -h Display help text
###Example:
###     copymbr
scripthelp "$0" "$@" && exit 0
if [ -z "$2" ] ; then scripthelp "$0" "--help" ; exit 0 ; fi

src=$1
dst=$2

echo dd if=$src of=$dst bs=512 count=1 conv=notrunc
dd if=$src of=$dst bs=512 count=1 conv=notrunc
