#!/bin/bash

#Script Name:	cpptags
#Date:		Thu Dec 14 21:58:15 CST 2006
#AUTHOR:	xiaoranzzz


# COLOR
NOR="\033[0m"
BOLD="\033[1m"
RED="\033[91m"
YEL="\033[93m"
GRE="\033[92m"



APPNAME="cpptags"
APPVER="0.1"
APPDESC="Generate c++ tags using ctags"
APPUSAGE="[ctags Option] (Files)"
EXAMPLE="cpptags -f stdcpp.tags /usr/include/c++"


ARGS=$*

if [ -z "$ARGS" ] || [ "$ARGS" = "-h" ] ;then
	echo "$APPNAME V$APPVER"
	echo -e "\t $APPDESC"
	echo -e " -h\tDisplay this."
	echo -e " -e\tWhere am I." 
	echo -e "Usage: $0 $APPUSAGE"
	if [ ! -z "$EXAMPLE" ];then 
	    echo -e "Example: $EXAMPLE"
	fi
	exit 0
fi

if [ "$1" = "-e" ] ; then
    echo $0
    exit 0
fi

echo ctags -R --c++-kinds=+p --fields=+iaS --extra=+q --languages=c++ $*
ctags -R --c++-kinds=+p --fields=+iaS --extra=+q --languages=c++ $*


