#!/bin/sh
###foreach_dir v0.1
###     - foreach_dir
###     - Written by xiaoranzzz, 2010-05-07
###Usage:
###     foreach_dir
###Option:
###     -h Display help text
###Example:
###     foreach_dir
scripthelp "$0" "$@" && exit 0
if [ -z "$1" ] ; then scripthelp "$0" "--help" ; exit 0 ; fi
exp=*
cmd=echo

[ -n "$1" ] && exp=$1 && shift
[ -n "$*" ] && cmd="$@"

for i in $exp ; do [ -f "$i" ] && $cmd "$i" ; done

