#!/bin/sh
###foreach v0.1
###     - foreach
###     - Written by duel, 2010-05-07
###Usage:
###     foreach
###Option:
###     -h Display help text
###Example:
###     foreach
#scripthelp "$0" "$@" && exit 0
#if [ -z "$1" ] ; then scripthelp "$0" "--help" ; exit 0 ; fi

exp=*
cmd=echo

[ -n "$1" ] && exp=$1 && shift
[ -n "$*" ] && cmd="$@"

for i in $exp ; do $cmd "$i" ; done
