#!/bin/sh
###format_xml v0.1
###     - format_xml
###     - Written by duel, 2008-06-26
###Usage:
###     format_xml
###Option:
###     -h Display help text
###Example:
###     format_xml
scripthelp "$0" "$@" && exit 0
#if [ -z "$1" ] ; then scripthelp "$0" "--help" ; exit 0 ; fi
if [ -n "$1" ] ; then
    exec sed -i -e "s/</\n</g" "$@"
else
    exec sed -e "s/</\n</g"
fi
