#!/bin/bash
#TEMPLATE BEGIN
APPNAME="fullurl"
APPAUTHOR="duel"
APPDATE="2007-03-26"
APPVER="0.1"
APPDESC="Generate full URL"
APPUSAGE="[Base URL]"
EXAMPLE="echo 1.jpg | fullurl http://www.google.com"

# NOCOLOR
NOR=;BOLD=;RED=;YEL=;GRE=
# COLOR
NOR="\033[0m";BOLD="\033[1m";RED="\033[91m";YEL="\033[93m";GRE="\033[92m"
# FUNCTIONS
function APPMSG() { if [ -n "$*" ] ; then echo -e $GRE"$*"$NOR ; fi ; } 
function APPMSG2() { if [ -n "$*" ] ; then APPMSG "\t$*" ; fi ; }
function APPWARN() { if [ -n "$*" ] ; then echo -e $RED"$*"$NOR ; fi ; }
function DisplayUsage() {
    APPMSG "$APPNAME V$APPVER\n  Written by $APPAUTHOR AT $APPDATE"
    APPMSG "$APPDESC"
    APPMSG " -h\tDisplay this information.\n -E\tEdit me."
    APPMSG "Usage: $0 $APPUSAGE"
    if [ -n "$EXAMPLE" ] ; then APPMSG "Example: $EXAMPLE" ; fi
    exit 1 
}
ARGS=$*
for i in $ARGS ; do
    case $i in 
        "-h" ) DisplayUsage ;;
        "-E" ) vim $0 ; exit $? ;;
    esac
done
#TEMPLATE END
if [ -z "$1" ] ; then 
    cat /dev/stdin
    exit 0
fi

BASEURL=`echo $1 | sed -e "s/\ /%20/g"`
if ! echo "$BASEURL" | grep "://" >/dev/null ; then
    BASEURL="http://$BASEURL"
fi
PROTOCOL=`urlprotocol "$BASEURL"`
DOMAIN=`urldomain "$BASEURL"`
DIRECTORY=`urlpath "$BASEURL"`
#echo $BASEURL
#echo $DOMAIN
#echo $DIRECTORY

{
while read -s RELATEURL ; do

    if echo "$RELATEURL" | grep "://" > /dev/null ; then
        RELATEURL=$RELATEURL
    elif echo "$RELATEURL" | egrep "^\/" > /dev/null ; then
        RELATEURL="$PROTOCOL://$DOMAIN$RELATEURL"
    else
        RELATEURL="$PROTOCOL://$DOMAIN$DIRECTORY$RELATEURL"
    fi
    echo "$RELATEURL"

done
} < /dev/stdin
