#!/bin/sh
###git-acommit v0.1
###     - git-acommit
###     - Written by xiaoranzzz, 2012-02-03 02:33
###Usage:
###     git-acommit
###Option:
###     -h Display help text
###Example:
###     git-acommit
#scripthelp "$0" "$@" && exit 0
#if [ -z "$1" ] ; then scripthelp "$0" "--help" ; exit 0 ; fi
git add "$@"
exec git commit -m "Add/Update '$*'"

