#!/bin/bash
APPNAME="grepurl"
APPAUTHOR="xiaoranzzz"
APPDATE="2007-04-02"
APPVER="0.1"
APPDESC="Grep all urls Out"
APPUSAGE=""
APPEXAMPLE="cat index.html | grepurl"
APPOPTION=""

#source `APPLIB "AppUsage"` || exit -1
#if [ -z "$*" ] ; then APPHELP ; exit 0 ; fi

    sed -e "s/\"/\'/g" -e "s/\ *=\ */=/g" -e "s/=\([^'\ ><]*\)\ /='\1'/g" -e "s/\('http:\/\/[^']*'\)/href=\1/g" | grep -io "href='[^']*'" | sed -e "s/^[^']*'//g" -e "s/'[^']*$//g"





