#!/bin/sh
###img-format v0.1
###     - img-format
###     - Written by xiaoranzzz, 2009-06-19
###Usage:
###     img-format
###Option:
###     -h Display help text
###Example:
###     img-format
scripthelp "$0" "$@" && exit 0
if [ -z "$1" ] ; then scripthelp "$0" "--help" ; exit 0 ; fi

