#!/bin/sh
###img-select-mv v0.1
###     - img-select-mv
###     - Written by duel, 2008-09-11
###Usage:
###     img-select-mv
###Option:
###     -h Display help text
###Example:
###     img-select-mv
scripthelp "$0" "$@" && exit 0
for arg in "$@" ; do
    [ "$arg" == "selected" ] && shift
done
if [ -z "$1" ] ; then scripthelp "$0" "--help" ; exit 0 ; fi

[ -d "selected" ] || mkdir -v "selected"

exec img-select "$@" | xargs -I img mv -v -- img "selected/"
