#!/bin/bash

#Script Name:	imgsearch
#Date:		Sat Dec 23 17:12:51 CST 2006
#AUTHOR:	xiaoranzzz


# COLOR
NOR="\033[0m"
BOLD="\033[1m"
RED="\033[91m"
YEL="\033[93m"
GRE="\033[92m"



APPNAME="imgsearch"
APPVER="0.1"
APPDESC=""
APPUSAGE="(keyworkd) [frompage] [topage]"
EXAMPLE=""


ARGS=$*

if [ -z "$ARGS" ] || [ "$ARGS" = "-h" ] ;then
	echo "$APPNAME V$APPVER"
	echo -e "\t $APPDESC"
	echo -e " -h\tDisplay this."
	echo -e " -e\tWhere am I." 
	echo -e "Usage: $0 $APPUSAGE"
	if [ ! -z "$EXAMPLE" ];then 
	    echo -e "Example: $EXAMPLE"
	fi
	exit 0
fi

if [ "$1" = "-e" ] ; then
    echo $0
    exit 0
fi

KEYWORD=$1
FROM_PAGE=$2
TO_PAGE=$3

if [ -z "$FROM_PAGE" ]; then
    FROM_PAGE=1
fi

if [ $FROM_PAGE -le 0 ]; then
    FROM_PAGE=1
fi

if [ -z "$TO_PAGE" ]; then
    TO_PAGE=$FROM_PAGE
fi

#Google image
function  google() {
    local GBASEURL="http://images.google.com/images?q=###KEYWORD###&start=###START###&imgsz=xxlarge&ndsp=20&svnum=10&hl=en&lr=&safe=off&filter=0"
    local GKEYWORD=$1
    local GSTART=$((($2-1)*21))
    echo $GBASEURL|sed "s/###KEYWORD###/$GKEYWORD/g"|sed "s/###START###/$GSTART/g"
}

#BAIDU image
function baidu() {
    local BBASEURL="http://image.baidu.com/i?z=3&cl=2&ct=201326592&sn=&lm=-1&cm=1&sc=0&bu=&rn=21&tn=baiduimage&word=###KEYWORD###&pn=###START###"
    local BKEYWORD=`echo $1 | iconv -f UTF8 -t GB2312`
    local BSTART=$((($2-1)*18))
    echo $BBASEURL|sed "s/###KEYWORD###/$BKEYWORD/g"|sed "s/###START###/$BSTART/g"
}

total=$(($TO_PAGE-$FROM_PAGE+1))

declare -i searchGoogle=1;
declare -i searchBaidu=0;

for ((i=$FROM_PAGE;i<=$TO_PAGE;i++)); do
    cur=$(($i-$FROM_PAGE+1))
    echo [$cur/$total] seaching for $KEYWORD,page $i >> /dev/stderr
    if [ $searchGoogle -eq 1 ]; then
	gResult=$(mywget -q -O- `google "$KEYWORD" "$i"` | imglink)
	gCount=0
	for sr in $gResult ; do
	    echo "$sr" ;
	    gCount=$((gCount+1))
	done
#	echo $gCount
	if [ $gCount -lt 20 ]; then searchGoogle=0 ; fi
    fi
    if [ $searchBaidu -eq 1 ]; then
	bResult=$(mywget -q -O- `baidu "$KEYWORD" "$i"` | imglink)
	bCount=0
	for si in $bResult ; do 
	    echo "$sr" 
	    bCount=$((bCount+1))
	done
#	echo $bCount
	if [ $bCount -lt 17 ]; then searchBaidu=0 ; fi
    fi
done




