#!/bin/bash

#Script Name:	imgsearch
#Date:		Sat Dec 23 17:12:51 CST 2006
#AUTHOR:	xiaoranzzz


# COLOR
NOR="\033[0m"
BOLD="\033[1m"
RED="\033[91m"
YEL="\033[93m"
GRE="\033[92m"



APPNAME="imgsearch"
APPVER="0.1"
APPDESC=""
APPUSAGE="(keyworkd) [page]"
EXAMPLE=""


ARGS=$*

if [ -z "$ARGS" ] || [ "$ARGS" = "-h" ] ;then
	echo "$APPNAME V$APPVER"
	echo -e "\t $APPDESC"
	echo -e " -h\tDisplay this."
	echo -e " -e\tWhere am I." 
	echo -e "Usage: $0 $APPUSAGE"
	if [ ! -z "$EXAMPLE" ];then 
	    echo -e "Example: $EXAMPLE"
	fi
	exit 0
fi

if [ "$1" = "-e" ] ; then
    echo $0
    exit 0
fi

KEYWORD=${1/\ /+}
PAGE=$2

[ -z "$PAGE" ] &&  PAGE=1
[ $PAGE -le 0 ] && PAGE=1

googleimg "$KEYWORD" "$PAGE" 




