#!/bin/sh
###lhadir v0.1
###     - lhadir
###     - Written by xiaoranzzz, 2009-06-24
###Usage:
###     lhadir
###Option:
###     -h Display help text
###Example:
###     lhadir
scripthelp "$0" "$@" && exit 0
if [ -z "$1" ] ; then scripthelp "$0" "--help" ; exit 0 ; fi

while [ -n "$1" ] ; do
	tmplha=`mktemp -t`
	[ -f "$tmplha" ] && rm -f "$tmplha"
	pushd "$1"
	lha -co6 "$tmplha" *
	popd
	if [ -f "$tmplha" ] ; then
		mv "$tmplha" "$1.lha" >/dev/null 2>&1
	else
		echo "Error when packing $1"
	fi
	shift
done
