#!/bin/bash
###APPNAME:	linepipe
###APPAUTHOR:	duel
###APPDATE:	2007-03-29
###APPVER:	0.2
###APPDESC:	pipe line by line as arguments of the command specified.
###APPUSAGE:	(Command)
###APPEXAMPLE:	cat urllist | linepipe wget
###APPOPTION:	
###APPOPTSTR:	
plhelp "$0" "$@" && exit 0

LINECMD="$@"
if [ -z "$LINECMD" ] ; then LINECMD="echo" ; fi
declare -a LINES
declare -i Count=0
declare -i Index=0
[ -n "$LINEPIPE_DEBUG" ] && echo "linepipe:debug LINECMD=\"$LINECMD\"" >&2
while read -s LINE ; do
    LINES[$Count]="$LINE"
    (( Count++ ))
    echo -en "\r***LinePipe*** : $Count lines read ...         " >&2
done
echo "" >&2
while (( Index < Count )) ; do
    ARGS="${LINES[$Index]}"
    (( Index++ ))
    CURCMD=${LINECMD/\%J/$Index\/$Count}
    CURCMD=${CURCMD/\%I/$Index}
    CURCMD=${CURCMD/\%C/$Count}
    $CURCMD "$ARGS"
done


