#!/bin/bash
#TEMPLATE BEGIN
APPNAME="loadwow"
APPAUTHOR="xiaoranzzz"
APPDATE="2007-01-31"
APPVER="0.1"
APPDESC="Load War of Warcraft"
APPUSAGE=""
EXAMPLE=""

# NOCOLOR
NOR=;BOLD=;RED=;YEL=;GRE=
# COLOR
NOR="\033[0m";BOLD="\033[1m";RED="\033[91m";YEL="\033[93m";GRE="\033[92m"
# FUNCTIONS
function APPMSG() { if [ -n "$*" ] ; then echo -e $GRE"$*"$NOR ; fi ; } 
function APPMSG2() { if [ -n "$*" ] ; then APPMSG "\t$*" ; fi ; }
function APPWARN() { if [ -n "$*" ] ; then echo -e $RED"$*"$NOR ; fi ; }
function DisplayUsage() {
    APPMSG "$APPNAME V$APPVER\n  Written by $APPAUTHOR AT $APPDATE"
    APPMSG "$APPDESC"
    APPMSG " -h\tDisplay this information.\n -E\tEdit me."
    APPMSG "Usage: $0 $APPUSAGE"
    if [ -n "$EXAMPLE" ] ; then APPMSG "Example: $EXAMPLE" ; fi
    exit 1 
}
ARGS=$*
#if [ -z "$ARGS" ] ; then DisplayUsage ; fi
for i in $ARGS ; do
    case $i in 
        "-h" ) DisplayUsage ;;
        "-E" ) vim $0 ; exit $? ;;
    esac
done
#TEMPLATE END

#X :3 -ac &   # Launches a new X session on display 3 
#mount /windows/d
cd "/d:/Games/World of Warcraft/"   # Goto WoW dir 
#sleep 2   # Forces the system to have a break for 2 seconds 
#DISPLAY=:3 wine WoW.exe -opengl   # Launches WoW
wine WoW.exe -opengl
