#!/bin/bash
###APPNAME:     markfile
###APPAUTHOR:   geek
###APPDATE:     2007-11-09
###APPVER:      0.1
###APPDESC:     mark files by prefix a char(default as 'M')
###APPUSAGE:    [char] files...
###APPEXAMPLE:  markfile N *
###APPOPTION:   
scripthelp "$0" "$@" && exit 0
if [ -z "$1" ] ; then scripthelp "$0" "--help" ; exit 0 ; fi

c=$1
if [ ${#c} != 1 ] ; then
    echo "Error: \"$1\" contains more than 1 char" >/dev/stderr
    exit 1
fi
shift 1

count=0;
while [ -n "$1" ] ; do
    if [ -e "$1" ] ; then
        dn=`dirname "$1"`
        bn=`basename "$1"`
        if [ ${bn:1:1} == "_" ] ; then bn=${bn:2} ; fi
        echo "$dn/${c}_$bn"
        mv "$1" "$dn/${c}_$bn"
        ((count++))
    else
        echo "Error: $1 not exist"
    fi
    shift 1
done
echo "$count file(s) marked as $c" >/dev/stderr
exit 0

