#!/bin/sh
SDCARD=MILESTONE
do_unmount=
SUBDIR=

while [ -n "$1" ] ; do
    case "$1" in
        -u|--unmount)
            do_unmount=1;;
        *)
            SUBDIR="$1";;
    esac
    shift
done

if [ -n "$do_unmount" ] ; then
    echo "Unmounting $SDCARD..."
    if pumount "/dev/disk/by-label/$SDCARD" ; then
        echo OK
    fi
#    gnome-umount -vt -p "$SDCARD"
#    umount -v "/media/$SDCARD"
else
    [ -r . ] || cd ~/
    echo "Mounting $SDCARD"
    if pmount -A -e -u 002 "/dev/disk/by-label/$SDCARD" "$SDCARD" ; then echo OK ; fi
    exec mc "/media/$SDCARD/$SUBDIR" ~/public
fi
