#!/bin/sh
###output v0.1
###     - output stdin to file
###     - Written by duel, 2009-01-13
###Usage:
###     output filename
###Option:
###     -h Display help text
###Example:
###     output foo.bar
scripthelp "$0" "$@" && exit 0
if [ -z "$1" ] ; then scripthelp "$0" "--help" ; exit 0 ; fi
cat >>"$1"
