#!/bin/sh
###playfind v0.1
###     - playfind
###     - Written by xiaoranzzz, 2009-02-04
###Usage:
###     playfind [folder]
###Option:
###     -h Display help text
###Example:
###     playfind music
scripthelp "$0" "$@" && exit 0
if [ -z "$1" ] ; then scripthelp "$0" "--help" ; exit 0 ; fi
tmpfile=`mktemp -q .XXXX-playfind`
find "$@" -iname "*.mp3" >"$tmpfile"
mpg123 --list "$tmpfile" --control --shuffle 
rm -f "$tmpfile"
