#!/bin/sh
###r-mplayer v0.1
###     - r-mplayer
###     - Written by duel, 2009-05-26
###Usage:
###     r-mplayer
###Option:
###     -h Display help text
###Example:
###     r-mplayer
scripthelp "$0" "$@" && exit 0
if [ -z "$1" ] ; then scripthelp "$0" "--help" ; exit 0 ; fi


if ! mplayer "$@" >~/r-mplayer.log ; then
   zenity --text-info --filename=$HOME/r-mplayer.log
fi

