#!/bin/sh
###r-qemu-xp v0.1
###     - r-qemu-xp
###     - Written by xiaoranzzz, 2010-11-05
###Usage:
###     r-qemu-xp
###Option:
###     -h Display help text
###Example:
###     r-qemu-xp
#scripthelp "$0" "$@" && exit 0
#if [ -z "$1" ] ; then scripthelp "$0" "--help" ; exit 0 ; fi
exec r-qemu -kvm -hda /myplace/emuos/windows_xp.raw "$@"
