#!/bin/sh
###r-quick-cmd v0.1
###     - r-quick-cmd
###     - Written by duel, 2009-01-14
###Usage:
###     r-quick-cmd
###Option:
###     -h Display help text
###Example:
###     r-quick-cmd
scripthelp "$0" "$@" && exit 0
if [ -z "$1" ] ; then scripthelp "$0" "--help" ; exit 0 ; fi

case $1 in
    1) cmd=x-terminal-emulator;;
    2) cmd="x-terminal-emulator -e mc";;
    3) cmd=r-firefox;;
    4) cmd=rox;;
    5) cmd=r-shutdown;;
    *) cmd=r-x-prompt;;    
esac
exec $cmd

