#!/bin/sh
###r-vncserver v0.1
###     - r-vncserver
###     - Written by duel, 2010-05-05
###Usage:
###     r-vncserver
###Option:
###     -h Display help text
###Example:
###     r-vncserver
#scripthelp "$0" "$@" && exit 0
#if [ -z "$1" ] ; then scripthelp "$0" "--help" ; exit 0 ; fi

if [ "$UID" == "1025" ] ; then
    display=:4
else
    display=:3
fi
[ -n "$1" ] && display=$1 && shift

#echo vncviewer -shared -quality 9 192.168.1.25$display "$@"

x-ask-passwd "vncserver 192.168.1.25$display\nasking for password:" "r-vncviewer" | vncpasswd -f | vncviewer -shared -quality 9 -passwd - 192.168.1.25$display&
