#!/bin/sh
###r-x-prompt v0.1
###     - command box with zenity interface
###     - Written by duel, 2009-01-14
###Usage:
###     r-x-prompt [title] [text] [default]
###Option:
###     -h Display help text
###Example:
###     r-x-prompt
scripthelp "$0" "$@" && exit 0


title="${1:-R-X-Prompt Box}"
text="${2:-Input commands to execute:}"
default="$3"
zenity="zenity --width=300"

function process {
    read cmd args
    if [ -z "$cmd" ] ; then
        exit 0;
    fi
    
    full_path=`which "$cmd"`
    if [ -z "$full_path" ] ; then
        $zenity --title "$title" --error --text "Error!\n$cmd: Command not found!"
        exit 1;
    fi
    exec "$full_path" $args
}


$zenity --title="$title" --entry --text="$text" --entry-text="$default" | process
