#!/bin/bash
###APPNAME="scriptrename"
###APPAUTHOR="duel"
###APPDATE="2007-03-30"
###APPVER="0.2"
###APPDESC="rename script and it's local link"
###APPUSAGE="(oldname) (newname)"
###APPEXAMPLE="scriptrename scriptrename mvscript"
###APPOPTION=""

source `APPLIB "AppUsage"` || exit -1
source `APPLIB "System"` || exit -1
source `APPLIB "ScriptDef"` || exit -1

if [ -z "$*" ] ; then APPHELP ; exit 0 ; fi

OLDNAME=`basename "$1" .$SCRIPTEXT`
NEWNAME=`basename "$2" .$SCRIPTEXT`

if [ -z "$NEWNAME" ] ; then APPHELP ; exit 0 ; fi
if [ "$OLDNAME" = "$NEWNAME" ] ; then APPHELP ; exit 0 ; fi
#APPMSG "Rename shellscript \"$OLDNAME\" to \"$NEWNAME\"\n"
#APPMSG "$SCRIPTDIR/$OLDNAME\n"
if [ -f "$SCRIPTDIR/$OLDNAME" ] ; then
    OLDSCRIPT="$SCRIPTDIR/$OLDNAME"
    OLDLINK="$SCRIPTBINDIR/$OLDNAME"
    NEWSCRIPT="$SCRIPTDIR/$NEWNAME"
    NEWLINK="$SCRIPTBINDIR/$NEWNAME"
else
    OLDSCRIPT="$SCRIPTDIR/$OLDNAME.$SCRIPTEXT"
    OLDLINK="$SCRIPTBINDIR/$OLDNAME"
    NEWSCRIPT="$SCRIPTDIR/$NEWNAME.$SCRIPTEXT"
    NEWLINK="$SCRIPTBINDIR/$NEWNAME"
fi


if [ -f "$OLDSCRIPT" ] ; then 
    APPMSG "Rename \"$OLDSCRIPT\" to \"$NEWSCRIPT\"\n"
    TrySudo mv "$OLDSCRIPT" "$NEWSCRIPT"
else
    echo \"$OLDSCRIPT\" not exist.
fi
if [ -L "$OLDLINK" ] ; then
    APPMSG "Link \"$OLDLINK\" to \"$NEWSCRIPT\"\n"
    TrySudo ln -sf "$NEWSCRIPT" "$OLDLINK"
    APPMSG "Rename \"$OLDLINK\" to \"$NEWLINK\"\n"
    TrySudo mv "$OLDLINK" "$NEWLINK"
else    
    echo \"$OLDLINK\" not exist.
fi



