#!/bin/sh
###sudo_if_need v0.1
###     - Invoke sudo if USER is not root
###     - Written by xiaoranzzz, 2008-04-05
###Usage:
###     sudo_if_need
###Option:
###     -h Display help text
###Example:
###     sudo_if_need
scripthelp "$0" "$@" && exit 0
if [ -z "$1" ] ; then scripthelp "$0" "--help" ; exit 0 ; fi

if [ "$USER" == "root" ] ; then
    "$@"
else
    sudo "$@"
fi
