#!/bin/sh
###totalcmd v0.1
###     - totalcmd
###     - Written by duel, 2008-12-24
###Usage:
###     totalcmd
###Option:
###     -h Display help text
###Example:
###     totalcmd

#resume=`/myplace/wine/bin/get-appdefault.pl "TotalCmd.exe"`
#/myplace/wine/bin/del-appdefault.pl "TotalCmd.exe"
#/myplace/wine/bin/set-appdefault.pl "TotalCmd.exe" browseui,ole32,oleaut32,rpcrt4,shlwapi,msvcrt=b | regedit -

#sleep 1
#DLLOVERRIDES='rpcrt4=b' cn_wine 'R:\Program\Fileman\TotalCmd\TotalCmd.exe'
#sleep 1
#echo -E "$resume" | regedit -

arch=32
if [ "AMD64" = "$PROCESSOR_ARCHITEW6432" ] ; then arch=64 ; fi
if [ "AMD64" = "$PROCESSOR_ARCHITECTURE" ] ; then arch=64 ; fi
if [ "$arch" = "64" ] ; then 
appdir=`cygpath -u "$FS_SYSTEM_APP"`
appname="totalcmd64.exe"
else
appdir=`cygpath -u "$FS_SYSTEM"`
appdir="$appdir/app32"
appname="totalcmd.exe"
fi
app="$appdir/fileman/totalcmd/$appname"
echo $app "$@"
if [ "$OSTYPE" == "cygwin" ] ; then
	exec "$app" "$@" &
else
	exec cn_wine "$app" "$@"
fi
