#!/bin/bash
###APPNAME:     umarkfile
###APPAUTHOR:   geek
###APPDATE:     2007-11-09
###APPVER:      0.1
###APPDESC:     unmark files marked by markfile
###APPUSAGE:    files...
###APPEXAMPLE:  markfile N *
###APPOPTION:   
scripthelp "$0" "$@" && exit 0
if [ -z "$1" ] ; then scripthelp "$0" "--help" ; exit 0 ; fi

count=0;
while [ -n "$1" ] ; do
    if [ -f "$1" ] ; then
        dn=`dirname "$1"`
        bn=`basename "$1"`
        if [ ${bn:1:1} == "_" ] ; then 
            bn=${bn:2}
            mv -v $1 $dn/$bn
            ((count++))
        fi
    else
        echo "Error: $1 not exist"
    fi
    shift 1
done
echo "$count file(s) unmarked"
exit 0

