#!/bin/bash
DEFAULT_MUSIC_DIR=/share/music

#TEMPLATE BEGIN
APPNAME="unpackmusic"
APPAUTHOR="duel"
APPDATE="2007-03-11"
APPVER="0.1"
APPDESC="unpack music album archive"
APPUSAGE="(rarfile) [extract_to]"
EXAMPLE="unpackmusic foo.rar /share/music"

# NOCOLOR
NOR=;BOLD=;RED=;YEL=;GRE=
# COLOR
NOR="\033[0m";BOLD="\033[1m";RED="\033[91m";YEL="\033[93m";GRE="\033[92m"
# FUNCTIONS
function APPMSG() { if [ -n "$*" ] ; then echo -e $GRE"$*"$NOR ; fi ; } 
function APPMSG2() { if [ -n "$*" ] ; then APPMSG "\t$*" ; fi ; }
function APPWARN() { if [ -n "$*" ] ; then echo -e $RED"$*"$NOR ; fi ; }
function DisplayUsage() {
    APPMSG "$APPNAME V$APPVER\n  Written by $APPAUTHOR AT $APPDATE"
    APPMSG "$APPDESC"
    APPMSG " -h\tDisplay this information.\n -E\tEdit me."
    APPMSG "Usage: $0 $APPUSAGE"
    if [ -n "$EXAMPLE" ] ; then APPMSG "Example: $EXAMPLE" ; fi
    exit 1 
}
ARGS=$*
if [ -z "$ARGS" ] ; then DisplayUsage ; fi
for i in $ARGS ; do
    case $i in 
        "-h" ) DisplayUsage ;;
        "-E" ) vim $0 ; exit $? ;;
    esac
done
#TEMPLATE END
MUSIC_RAR=$1
MUSIC_DIR=$2

if [ ! -f "$MUSIC_RAR" ] ; then APPWARN $MUSIC_RAR not exists. ; exit -1 ; fi
if [ -z "$MUSIC_DIR" ] ; then MUSIC_DIR=$DEFAULT_MUSIC_DIR ; fi

ALBUM=`echo "$MUSIC_RAR" | sed -e "s/.*\[//g" -e "s/\].*//g"`
PATH_EXTRACTED=$MUSIC_DIR/$ALBUM
if [ ! -d "$PATH_EXTRACTED" ] ; then mkdir "$PATH_EXTRACTED" ; fi
if [ ! -d "$PATH_EXTRACTED" ] ; then APPWARN $PATH_EXTRACTED not exsits. ; exit -1 ; fi

unrar x "$MUSIC_RAR" "*" "$PATH_EXTRACTED"




