#!/bin/sh
###unrarfolder v0.1
###     - unrarfolder
###     - Written by duel, 2009-02-04
###Usage:
###     unrarfolder
###Option:
###     -h Display help text
###Example:
###     unrarfolder
scripthelp "$0" "$@" && exit 0
if [ -z "$1" ] ; then scripthelp "$0" "--help" ; exit 0 ; fi


while [ -n "$1" ] ; do
    arch=$1
    dst=${arch/.rar//}
    unrar x "$arch" "$dst"
    shift
done
