#!/bin/sh
###usrdoc-view v0.1
###     - usrdoc-view
###     - Written by xiaoranzzz, 2008-02-16
###Usage:
###     usrdoc-view
###Option:
###     -h Display help text
###Example:
###     usrdoc-view
scripthelp "$0" "$@" && exit 0
if [ -z "$1" ] ; then scripthelp "$0" "--help" ; exit 0 ; fi

viewdir `usrdoc-find "$1"`


