#!/bin/sh
###usrdoc-find v0.1
###     - usrdoc-find
###     - Written by xiaoranzzz, 2008-02-16
###Usage:
###     usrdoc-find
###Option:
###     -h Display help text
###Example:
###     usrdoc-find
scripthelp "$0" "$@" && exit 0
if [ -z "$1" ] ; then scripthelp "$0" "--help" ; exit 0 ; fi

finddir "/usr/share/doc" "$@"
