#!/bin/sh
###wine-finddll v0.1
###     - wine-finddll
###     - Written by xiaoranzzz, 2008-04-14
###Usage:
###     wine-finddll
###Option:
###     -h Display help text
###Example:
###     wine-finddll
scripthelp "$0" "$@" && exit 0
if [ -z "$1" ] ; then scripthelp "$0" "--help" ; exit 0 ; fi

wined=~/.wine
sysd="$wined/dosdevices/c:/windows/system32/"
find "$sysd" -type f -iname "$1.dll"
