#!/bin/sh
###wine-installdll v0.1
###     - wine-installdll
###     - Written by xiaoranzzz, 2008-04-14
###Usage:
###     wine-installdll
###Option:
###     -h Display help text
###Example:
###     wine-installdll
scripthelp "$0" "$@" && exit 0
if [ -z "$1" ] ; then scripthelp "$0" "--help" ; exit 0 ; fi

wine=~/.wine
sys32="$wine/dosdevices/c:/windows/system32"

toLower() {
  echo $1 | tr "[:upper:]" "[:lower:]" 
} 

for dll in "$@" ; do
    [ -f "$dll" ] || continue
    l_dll=`echo "$dll" | tr '[:upper:]' '[:lower:]'`
    cp -iv "$dll" "$sys32/$l_dll"
    if [ -f "$sys32/$l_dll" ] ; then
        pushd "$sys32"
        cn_wine regsvr32 "$l_dll"
        echo "$l_dll" >>"wine-installdll.txt"
        popd
    fi
done

