#!/bin/sh
###xexec v0.1
###     - xexec
###     - Written by xiaoranzzz, 2008-09-06
###Usage:
###     xexec
###Option:
###     -h Display help text
###Example:
###     xexec
scripthelp "$0" "$@" && exit 0
if [ -z "$1" ] ; then scripthelp "$0" "--help" ; exit 0 ; fi
DISPLAY=:0 exec "$@"
