#!/bin/sh
###APPDATE="Wed Dec 27 03:23:39 CST 2006"
###APPAUTHOR=xiaoranzzz
###APPNAME="zhreader-epiphany"
###APPVER="0.1"
###APPDESC="open zip file,read it in firefox"
###APPUSAGE=<zipfilename>
###APPEXAMPLE=""
if [ -z "$*" ] ; then  formathelp "$0" ; exit 0 ; fi
plhelp "$0" "$@" && exit 0;

if [ -f "$1" ] ; then
    fn=`markfile R "$1"`
    zhtm "$fn" "epiphany"
else
    echo "\"$1\" not exist"
fi

