#!/bin/bash
###renameext v0.1
###     - pattern base rename utility
###     - Written by xiaoranzzz
###Usage:
###     renameext [options] pattern files...
###Options:
###     -h Display help text
###     -t Test only
###Example:
###     renameext "\.mp3/\.ogg/g" *
###     find . | renameext "\.window/\.linux/g"

scripthelp $0 "$@" && exit 0
if [ -z "$*" ] ; then 
    scripthelp $0 -h
    exit 0 
fi

TESTMODE=$1
if [ "$TESTMODE" == "-t" ] ; then
    shift
else
    TESTMODE=""
fi

PATTERN=$1
shift

OLDLIST=`mktemp`
NEWLIST=`mktemp`
declare -i count=0
declare -i index=0
declare -a files=
declare -i USETEMP=10

function addFile {
    files[$count]="$1"
    ((count++))
    echo -en "[$count] Reading filelist ...                  \r"
}

if [ -z "$1" ] ; then
    while read -s LINE ; do
        addFile "$LINE"
    done
else
    while [ -n "$1" ] ; do
        addFile "$1"
        shift    
    done
fi

echo ""

function doRename {
    local OLDFILE=$1
    local NEWFILE=$2
    [ -z "$NEWFILE" ] && return
    [ -z "$OLDFILE" ] && return
    if [ "$NEWFILE" != "$OLDFILE" ] ; then
        echo "[$index/$count] \"$OLDFILE\" => \"$NEWFILE\""
	[ -z "$TESTMODE" ] && mv "$OLDFILE" "$NEWFILE"
    else
	echo -en "[$index/$count] Ingore \"$OLDFILE\"                                \r"
    fi
    shift
}

if [ $count -gt $USETEMP ] ; then
    index=0
    while ((index<count)) ; do
        echo ${files[$index]} >>"$OLDLIST"
        ((index++))
        echo -en "[$index/$count] Writing filelist ...                           \r"
    done
    echo ""
    sed -e "s/$PATTERN" "$OLDLIST" >"$NEWLIST"
    index=0
    while read -s NEWNAME ; do
        OLDNAME=${files[$index]}
        ((index++))
        doRename "$OLDNAME" "$NEWNAME"
    done <"$NEWLIST"
else
    index=0
    while ((index<count)) ; do
        OLDNAME=${files[$index]}
        ((index++))
        NEWNAME=`echo "$OLDNAME" | sed -e "s/$PATTERN"` 
        doRename "$OLDNAME" "$NEWNAME"
    done
fi

echo ""
[ -e "$OLDLIST" ] && unlink "$OLDLIST"
[ -e "$NEWLIST" ] && unlink "$NEWLIST"

exit 0




