#!/bin/bash
APPNAME="urlrule_test"
APPAUTHOR="xiaoranzzz"
APPDATE="2007-03-31"
APPVER="0.1"
APPDESC="Test urlrule"
APPUSAGE="[OPTIONS] (URL)"
APPEXAMPLE=""
APPOPTION="" #"h:Display this text|E:Edit me"
APPOPTSTR="" #"hE"

source `APPLIB "URLRule"` || exit -1
source `APPLIB "AppUsage"` || exit -1
if [ -z "$*" ] ; then APPHELP ; exit 0 ; fi

URL="$URLRULE_URL"

if [ -z "$URL" ] ; then APPHELP ; exit -1 ; fi

APPMSG "Test urlrule on \"$URL\"\n"
urlrule "$@"





